fix: removed a bunch of uneeded  builds for us

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,18 +1,23 @@
 name: CI
 on:
   - push
-  - pull_request
+
 permissions: {}
 jobs:
   check-latest-versions:
     permissions:
       contents: read
-    runs-on: 'ubuntu-24.04'
+    runs-on: "ubuntu-24.04"
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-#      - name: Check latest versions
-#        run: ./check-latest-versions.sh
+      - name: Make sure we don't build and can't publish
+        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          echo "Error: This workflow should only run on version tags (refs/tags/v*)"
+          exit 1
+  #      - name: Check latest versions
+  #        run: ./check-latest-versions.sh
   build:
     permissions:
       contents: read
@@ -23,34 +28,18 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - os: 'ubuntu-24.04'
-            platform: 'linux-x64'
-          - os: 'ubuntu-24.04'
-            platform: 'linux-armv6'
-          - os: 'ubuntu-24.04'
-            platform: 'linuxmusl-x64'
-          - os: 'ubuntu-24.04'
-            platform: 'linux-ppc64le'
-          - os: 'ubuntu-24.04'
-            platform: 'linux-riscv64'
-          - os: 'ubuntu-24.04'
-            platform: 'linux-s390x'
-          - os: 'ubuntu-24.04'
-            platform: 'dev-wasm32'
-          - os: 'ubuntu-24.04'
-            platform: 'win32-ia32'
-          - os: 'ubuntu-24.04'
-            platform: 'win32-x64'
-          - os: 'ubuntu-24.04'
-            platform: 'win32-arm64v8'
-          - os: 'macos-15-intel'
-            platform: 'darwin-x64'
-          - os: 'macos-15'
-            platform: 'darwin-arm64v8'
-          - os: 'ubuntu-24.04-arm'
-            platform: 'linux-arm64v8'
-          - os: 'ubuntu-24.04-arm'
-            platform: 'linuxmusl-arm64v8'
+          - os: "ubuntu-24.04"
+            platform: "linux-x64"
+          - os: "ubuntu-24.04"
+            platform: "linux-armv6"
+          - os: "ubuntu-24.04"
+            platform: "win32-x64"
+          - os: "macos-15-intel"
+            platform: "darwin-x64"
+          - os: "macos-15"
+            platform: "darwin-arm64v8"
+          - os: "ubuntu-24.04-arm"
+            platform: "linux-arm64v8"
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -65,7 +54,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: build-${{ matrix.platform }}
-          path: '*.tar.gz'
+          path: "*.tar.gz"
           compression-level: 0
           retention-days: 1
           if-no-files-found: error
@@ -79,7 +68,7 @@ jobs:
       - name: Install Node.js
         uses: actions/setup-node@v5
         with:
-          node-version: '24'
+          node-version: "24"
       - name: Checkout
         uses: actions/checkout@v4
       - name: Download build artifacts
@@ -93,7 +82,7 @@ jobs:
       - name: Generate release notes
         run: ./generate-release-notes.sh
       - name: Create GitHub release for tag
-#        if: startsWith(github.ref, 'refs/tags/v')
+        if: startsWith(github.ref, 'refs/tags/v')
         uses: ncipollo/release-action@v1
         with:
           artifacts: npm-workspace.tar.xz
